---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gitops-project
spec:
  compositeTypeRef:
    apiVersion: skyway.realtor.com/v1alpha1
    kind: xGitopsProject
  resources:
    - name: Namespace
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: PATCHED
          annotations:
            "crossplane.io/external-name": PATCHED
          labels:
            "skyway.realtor.com/project-name": PATCHED
        spec:
          forProvider:
            name: PATCHED
            manifest:
              apiVersion: v1
              kind: Namespace
          providerConfigRef:
            name: kubernetes-provider
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.name"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.name"
          toFieldPath: "spec.forProvider.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.name"
          toFieldPath: "metadata.annotations['crossplane.io/external-name']"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.name"
          toFieldPath: "metadata.labels['skyway.realtor.com/project-name']"
    - name: ArgoCDProject
      base:
        apiVersion: projects.argocd.crossplane.io/v1alpha1
        kind: Project
        metadata:
          name: PATCHED
          annotations:
            "crossplane.io/external-name": PATCHED
          labels:
            "skyway.realtor.com/project-name": PATCHED
        spec:
          forProvider:
            name: PATCHED
          providerConfigRef:
            name: provider-argocd
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.name"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.name"
          toFieldPath: "spec.forProvider.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.name"
          toFieldPath: "metadata.annotations['crossplane.io/external-name']"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.name"
          toFieldPath: "metadata.labels['skyway.realtor.com/project-name']"
    - name: GithubRepository
      base:
        apiVersion: repo.github.upbound.io/v1alpha1
        kind: Repository
        metadata:
          name: PATCHED
          annotations:
            "crossplane.io/external-name": PATCHED
          labels:
            "skyway.realtor.com/project-name": PATCHED
        spec:
          forProvider:
            allowRebaseMerge: true
            allowSquashMerge: false
            allowAutoMerge: false
            allowMergeCommit: false
            autoInit: true
            defaultBranch: main
            hasDiscussions: false
            hasIssues: false
            hasProjects: false
            hasWiki: false
            visibility: public
          providerConfigRef:
            name: provider-github
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.name"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.name"
          toFieldPath: "metadata.annotations['crossplane.io/external-name']"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.name"
          toFieldPath: "metadata.labels['skyway.realtor.com/project-name']"
    - name: Prod appset
      base:
        apiVersion: repo.github.upbound.io/v1alpha1
        kind: RepositoryFile
        metadata:
          name: argocd-appset-prod
          labels:
            "skyway.realtor.com/project-name": PATCHED
        spec:
          forProvider:
            branch: main
            commitAuthor: Cabe Waldrop
            commitEmail: cabe.waldrop1985@gmail.com
            commitMessage: Testing things out
            content: "**/*.tfstate"
            file: .gitignore
            overwriteOnCreate: true
            repositorySelector:
              matchLabels:
                skyway.realtor.com/project-name: PATCHED
          providerConfigRef:
            name: provider-github
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.name"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.name"
          toFieldPath: "metadata.annotations['crossplane.io/external-name']"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.name"
          toFieldPath: "metadata.labels['skyway.realtor.com/project-name']"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.name"
          toFieldPath: "spec.forProvider.repositorySelector.matchLabels['skyway.realtor.com/project-name']"
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgitopsprojects.skyway.realtor.com
spec:
  group: skyway.realtor.com
  names:
    kind: xGitopsProject
    plural: xgitopsprojects
  claimNames:
    kind: GitopsProject
    plural: gitopsprojects
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
